""" Builds ament_index.
"""

load(
    "@com_github_mvukov_rules_ros2//repositories:version_header.bzl",
    "version_header",
)
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_library")

version_header(
    name = "ament_index_cpp_version_h",
    package_include = "ament_index_cpp",
    package_xml = "ament_index_cpp/package.xml",
)

cc_library(
    name = "ament_index_cpp",
    srcs = glob(["ament_index_cpp/src/*.cpp"]),
    hdrs = glob([
        "ament_index_cpp/include/ament_index_cpp/*.hpp",
        "ament_index_cpp/include/ament_index_cpp/*.h",
    ]) + [":ament_index_cpp_version_h"],
    includes = [
        "ament_index_cpp/include",
        "include",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "ament_index_python",
    srcs = glob(["ament_index_python/ament_index_python/*.py"]),
    imports = ["ament_index_python"],
    visibility = ["//visibility:public"],
)
